permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: Scattered Gonk
description: 6379623372707379636830733173
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true